import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from './components/Footer'
import Navbar from './components/Navbar'

export default function Home() {

  const boxes = [
    {
          title:"Send & receive easily",
          note:"Send and receive crypto assets efficiently with breew app",
          img:"/Group 8706.png"
  },
  {
    title:"Invest in real time",
    note:"Invest live without disruption and interruption from 3rd parties.",
    img:"/Group 8704.png"
},
{
  title:"Send & receive easily",
  note:"Send and receive crypto assets efficiently with breew app",
  img:"/Group 8702.png"
},


]

const cryptos = [
  {
    title:"Download the app",
    note:"The Breew app is available on apple store and playstore for easy downloads",
    img:"/Group 8724.png",
    no:"1."
  },
  {
    title:"Create your wallet",
    note:"Create your own Breew wallet with the fastest flow and the most simple layouts",
    img:"/Group 8725.png",  no:"2."
  },
  {
    title:"Buy and trade crypto",
    note:"Conduct speedy crypto transactions using Breew app today",
    img:"/Group 8726.png",  no:"3."
  },
]


const secures = [
  {
    heading:"0",
    title:"Security incidents"
  },
  {
    heading:"256 bits",
    title:"AES encryption"
  }
  ,
  {
    heading:"100%",
    title:"Encrypted data"
  },
  {
    heading:"CISA+",
    title:"Security Certification"
  }
]

const testimonials = [
  {
    heading:"Transactions are swift",
    note:" I was skeptical about using it first,but now I'm happy I did. All transactions went through very fast. I am going to be a returning user.",
    avatar:"/Ellipse 152.png",
    name:"Sandree",
    rate:"/Group 8695.png",
    media:"@sandree"
  },

  {
    heading:"Transactions are swift",
    note:" I was skeptical about using it first,but now I'm happy I did. All transactions went through very fast. I am going to be a returning user.",
    avatar:"/Ellipse 152.png",
    name:"Sandree",
    rate:"/Group 8695.png",
    media:"@sandree"
  },

  {
    heading:"Transactions are swift",
    note:" I was skeptical about using it first,but now I'm happy I did. All transactions went through very fast. I am going to be a returning user.",
    avatar:"/Ellipse 152.png",
    name:"Sandree",
    rate:"/Group 8695.png",
    media:"@sandree"
  },

  {
    heading:"Transactions are swift",
    note:" I was skeptical about using it first,but now I'm happy I did. All transactions went through very fast. I am going to be a returning user.",
    avatar:"/Ellipse 152.png",
    name:"Sandree",
    rate:"/Group 8695.png",
    media:"@sandree"
  },
]

const resources = [
  {
    heading:"Best platform to trade your BTC on your phone",
    date:"Mar 5, 2022",
    more:"Read more",
    img:"/Rectangle 4518.png"
  },
  {
    heading:"Best platform to trade your BTC on your phone",
    date:"Mar 5, 2022",
    more:"Read more",
    img:"/Rectangle 4518.png"
  },
  {
    heading:"Best platform to trade your BTC on your phone",
    date:"Mar 5, 2022",
    more:"Read more",
    img:"/Rectangle 4518.png"
  }
]
  return (
    <>
      <Head>
        <title>Breew-wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Woman hand holding iPhone 12 mockup (Black skin) (Mockuuups Studio).png" />
      </Head>

      <Navbar/>

      <header className='md:-mt-[70px] mt-[100px]'>
        <div className='flex justify-between items-center flex-col md:flex-row'>
          <div className='md:ml-[150px] -mt-[50px] px-4'>
            <h1 className='md:text-6xl text-4xl md:leading-[80px] font-bold'>Buy rapidly <br/>growing <span className='text-[#0582CA]'>crypto </span><br/>right from your<br/> phone</h1>
            <p className='md:w-[550px] mt-[25px]'>The fastest growing currencies are in high demand for smart functionalities . We take care of searching for the next high rising crypto for your speedy transactions</p>
            <div className='flex gap-[30px] mt-[50px]'>
            <button className="bg-[#0582CA] p-2 rounded-2xl w-[150px] text-white h-[60px] shadow">Download app</button>
            <button className="bg-white shadow p-2 rounded-2xl w-[150px] text-[#0582CA] h-[60px]">View pricing</button>
            </div>
          </div>
          <div className="relative z-2">
            <div className='absolute -left-[100px] top-[200px]'>
            <Image src="/dollar-dollar-color.png" width={150} height={50}/>
            </div>
            <div className='absolute right-[10px] top-[200px]'>
            <Image src="/eth-dynamic-color.png" width={150} height={50}/>
            </div>
            <div className='absolute left-[10px] bottom-[200px]'>
            <Image src="/yuan-dynamic-color (1).png" width={150} height={50}/>
            </div>
            <div className=' h-[400px] w-[300px] rounded-2xl absolute top-[20%] left-[10%] z-1' >

            </div>
            <div className='z-[666px]'>
            <Image src="/Woman hand holding iPhone 12 mockup (Black skin) (Mockuuups Studio).png" width={520} height={150}/>
            </div>
          
          </div>
        </div>
      </header>


<div className=' bg-[#EAEAEA] p-4 md:h-[1200px]'>
  <div className='flex flex-col items-center justify-center'>

    <div className='flex gap-[20px] mt-[50px]  '>
      <h3 className='text-[#0582CA] font-bold text-2xl'>01</h3> <span className='text-2xl text-[#929292]'>-</span> <h3 className='text-[#0582CA] font-bold text-2xl'>08</h3>
    </div>
    <div className='mt-[30px]'>
      <h1 className="md:text-5xl text-3xl font-bold text-center">Full featured to buy, <br/>trade and invest crypto</h1>
    </div>

    <div className="mt-[50px]">
      <div className='flex gap-[20px] flex-col md:flex-row'>
        <div className='md:w-[600px] h-[330px] bg-white rounded-2xl overflow-hidden p-4 flex justify-between items-center'>

          <div>
          <Image src="/Group 8698.png" width={50} height={100}/>
          <div className='mt-[30px] w-[300px]'>
            <h1 className='font-bold text-2xl mb-[10px]'>Buy 100+ crypto assets</h1>
            <p className="text-sm w-[250px]">Pick from a variety of crypto assets to buy,stake and sell</p>
          </div>
          </div>
          <Image src="/Group 8687.png" width={250} height={400}/>

        </div>

        <div className='md:w-[300px] h-[330px] bg-white rounded-2xl p-4'>

          <div className='mt-[70px]'>
          <Image src="/Group 8698.png" width={50} height={100}/>
          </div>
      
        <div className='mt-[30px] w-[300px]'>
            <h1 className='font-bold text-2xl mb-[10px]'>Secure wallet</h1>
            <p className="text-sm w-[250px]">Your crypto assets are protected by the latest security measures</p>
          </div>
        </div>
      </div>

      <div className='mt-[20px]'>
        <div className='grid grid-cols-1 md:grid-cols-3 gap-[20px]'>
          {boxes.map((item)=>{
            return (
              <div className="bg-white md:w-[300px] h-[330px] rounded-2xl p-4">
                 
                 <div className='mt-[70px]'>
          <Image src={item.img} width={50} height={100}/>
          </div>
      
        <div className='mt-[30px] w-[300px]'>
            <h1 className='font-bold text-2xl mb-[10px]'>{item.title}</h1>
            <p className="text-sm w-[250px]">{item.note}</p>
          </div>
              </div>
            )
          })}
        </div>
      </div>

    </div>
    <div className='flex gap-[30px] mt-[50px]'>
            <button className="bg-[#0582CA] p-2 rounded-2xl w-[150px] text-white h-[60px] shadow">Download app</button>
            <button className="bg-white shadow p-2 rounded-2xl w-[150px] text-[#0582CA] h-[60px]">View pricing</button>
            </div>

  </div>

</div>


<div className='mt-[150px] flex items-center justify-center'>

  <div className=' mx-auto flex gap-[30px] flex-col md:flex-row'>
    <div>
    <div className='flex gap-[20px] mt-[50px] mb-[30px] px-3'>
      <h3 className='text-[#0582CA] font-bold text-2xl'>02</h3> <span className='text-2xl text-[#929292]'>-</span> <h3 className='text-[#0582CA] font-bold text-2xl'>08</h3>
    </div>
    <div className='md:w-[400px] px-3'>
      <h1 className='font-bold text-4xl mb-[30px]'>A crypto wallet<br/> from the future</h1>
      <p>Get the latest updates and functionalities using Breew wallet as primary source of holding crypto</p>
    </div>
    <div>
      <ul className='font-bold flex flex-col gap-[20px] mt-[30px] px-3 md:px-0'>
        <li>
Lowest rates in tne market
        </li>
        <li>
Lowest rates in tne market
        </li>
        <li>
Lowest rates in tne market
        </li>
      </ul>
    </div>

    </div>
    <Image src="/Group 8711.png" width={450} height={100}/>
  </div>

</div>



<div className='mt-[150px] flex items-center justify-center'>

  <div className=' mx-auto flex gap-[80px] flex-col md:flex-row'>

  <Image src="/Group 8717.png" width={450} height={100}/>
    <div>
    <div className='flex gap-[20px] mt-[50px] mb-[30px] px-3 md:px-0'>
      <h3 className='text-[#0582CA] font-bold text-2xl'>03</h3> <span className='text-2xl text-[#929292]'>-</span> <h3 className='text-[#0582CA] font-bold text-2xl'>08</h3>
    </div>
    <div className='md:w-[400px] px-3'>
      <h1 className='font-bold text-4xl mb-[30px]'>Bullet proof <br/> security by design</h1>
      <p>Get all round security using flawless security measures and unbreakable design structure</p>
    </div>
    <div className='grid grid-cols-2 gap-[20px] mt-[50px]'>
     {
      secures.map((item)=>{
        return (
          <div className='bg-white w-[210px] h-[130px] rounded-2xl shadow border-[1px] flex flex-col items-center justify-center'>
            <h1 className='font-bold text-2xl mb-[6px]'>{item.heading}</h1>
            <p className='text-sm text-[#B0B0B0]'>{item.title}</p>
          </div>
        )
      })
     }
    </div>

    </div>
   
  </div>

</div>
    
<div className='md:mt-[300px] flex items-center justify-center mt-[100px] '>

  <div className='relative h-[700px] p-4'>

  <div className='absolute right-[30px] -top-[130px] z-50'>
    <div className="md:block hidden">
      <div className='relative z-10 '>
        <div className='absolute top-[90px] -left-[50px]'>
        <Image src="/thumb-up-dynamic-color.png" width={120} height={200}/>
        </div>
        <div className='absolute bottom-[90px] -right-[50px]'>
        <Image src="/chart-dynamic-color.png" width={120} height={200}/>
        </div>
      <Image src="/Group 8689.png" width={300} height={200}/>
      </div>
    
    </div></div>

  <div className='md:w-[900px] md:h-[400px] bg-[#0582CA] rounded-2xl text-white relative z-20' >
  <div className='absolute left-0 right-0 z-1 bottom-0 '>
        <Image src="/Mask group (3).png" width={850} height={100}/>
        </div>
    <div className="p-4 z-[9997777px]">
      <h2 className='text-4xl font-bold mt-[70px] '>Try the crypto wallet <br/>of the future, today</h2>

      <div className='flex gap-[30px] mt-[50px] flex-col md:flex-row'>
            <button className="bg-white p-3 rounded-2xl w-[230px] text-[#0582CA]  h-[60px] shadow flex gap-[20px] items-center justify-center text-sm font-bold cursor-pointer"> <Image src="/Group 8738.png" width={30} height={100}/>Download for IOS</button>
            <button className="bg-white shadow p-3 rounded-2xl w-[230px] text-[#0582CA] h-[60px] flex gap-[20px] items-center justify-center text-sm font-bold cursor-pointer"><Image src="/Group 8739.png" width={30} height={100}/>Download For Apple</button>
            </div>
    </div>
  </div>
  


  </div>
 
</div>





<div className='mt-[50px] flex items-center justify-center md:hidden '>

  <div className='relative md:h-[700px] p-4'>

  <div className='absolute right-[30px] -top-[130px] z-50'>
      <div className='relative z-10'>
        <div className='absolute top-[90px] -left-[50px]'>
        <Image src="/thumb-up-dynamic-color.png" width={120} height={200}/>
        </div>
        <div className='absolute bottom-[90px] md:-right-[50px] right-0'>
        <Image src="/chart-dynamic-color.png" width={120} height={200}/>
        </div>
      <Image src="/Group 8689.png" width={300} height={200}/>
      </div>
    
    </div>

  <div className='md:w-[900px] h-[380px] bg-[#0582CA] rounded-2xl text-white relative z-20 w-[400px]' >
  
    <div className="p-4 z-[9997777px]">
      

      
    </div>
  </div>
  


  </div>
 
</div>


























<div className='mt-[50px]'>

  <div className='flex flex-col items-center justify-center'>

  <div className='flex gap-[20px] mt-[50px] '>
      <h3 className='text-[#0582CA] font-bold text-2xl'>05</h3> <span className='text-2xl text-[#929292]'>-</span> <h3 className='text-[#0582CA] font-bold text-2xl'>08</h3>
    </div>
    <div className='mt-[30px]'>
      <h1 className="text-5xl font-bold text-center leading-[65px]">Get started with Breew <br/>in 3 easy steps</h1>
    </div>


    <div className='flex gap-[60px] mt-[30px] md:h-[700px] flex-col md:flex-row p-4'>
      <div className='relative bg-[#E6E6E6] rounded-2xl h-[500px]'>
        <Image src="/Mask group (4).png" width={350} height={200}/>
        <div className='absolute -bottom-[20px] -right-[70px]'>
        <Image src="/Group 8690.png" width={250} height={200}/>
        </div>
      </div>

      <div>
        <div>
          {
            cryptos.map((item)=>{
              return (
                <div className='flex gap-[30px] items-center mt-[30px] px-4'>
                  <Image src={item.img} width={50} height={50}/>
                  <div className='flex gap-[10px] px-3'>
                    <span className='font-bold'>{item.no}</span>
                    <div>
                    <h2 className="font-bold text-2xl">{item.title}</h2>
                    <p className='md:w-[350px] tex-sm'>{item.note}</p></div>
                  </div>
                </div>
              )
            })
          }


        </div>
        <div className='flex gap-[30px] mt-[50px] ml-[80px]'>
            <button className="bg-[#0582CA] p-2 rounded-2xl w-[150px] text-white h-[60px] shadow">Download app</button>
            <button className="bg-white shadow p-2 rounded-2xl w-[150px] text-[#0582CA] h-[60px]">View pricing</button>
            </div>
      </div>

    </div>

  </div>

</div>

     <div className='relative bg-[#E6E6E6]  md:h-[930px] p-[30px]'>
      <div className='  flex flex-col items-center justify-center'>
        <div>
        <div className='flex gap-[20px] mt-[50px] '>
      <h3 className='text-[#0582CA] font-bold text-2xl'>06</h3> <span className='text-2xl text-[#929292]'>-</span> <h3 className='text-[#0582CA] font-bold text-2xl'>08</h3>
    </div>
    <div className='flex items-center flex-col md:flex-row p-4'>
      <h1 className='font-bold text-4xl leading-[50px] md:w-[450px]'>See what people are<br/> saying about Breew</h1>

      <div className='flex gap-[30px] mt-[50px] md:ml-[80px]'>
            <button className="bg-[#0582CA] p-2 rounded-2xl w-[150px] text-white h-[60px] shadow font-bold">Download app</button>
            <button className="bg-white shadow p-2 rounded-2xl w-[150px] text-[#0582CA] h-[60px] font-bold">All reviews</button>
            </div>

    </div>
        </div>


        <div>
          <div className='grid grid-cols-1 md:grid-cols-2 gap-[30px] mt-[60px]'>
            {
              testimonials.map((item)=>{
                return(<div className="bg-white md:w-[400px] h-[250px] rounded-3xl p-4 ">
                  <div>
                    <h2 className="font-bold text-1xl">"{item.heading}"</h2>
                    <p className="mt-[30px] text-sm">{item.note}</p>
                  </div>

                  <div className='flex justify-around p-2 items-center mt-[30px]'>
                    <div className="flex gap-[20px]">
                    <Image src={item.avatar} width={50} height={50}/>
                    <div>
                      <h3 className='font-bold'>{item.name}</h3>
                      <p className="text-sm">{item.media}</p>
                    </div>
                    </div>
                    <div>
                    <Image src={item.rate} width={100} height={20}/>
                    </div>
                  
                  </div>

                </div>)
              })
            }
          </div>
        </div>

      </div>

     </div>


     <div className="md:h-[600px]">
<div className='  flex flex-col items-center justify-center'>
     <div>
        <div className='flex gap-[20px] mt-[50px] '>
      <h3 className='text-[#0582CA] font-bold text-2xl'>07</h3> <span className='text-2xl text-[#929292]'>-</span> <h3 className='text-[#0582CA] font-bold text-2xl'>08</h3>
    </div>
    <div className='flex items-center'>
      <h1 className='font-bold text-4xl leading-[50px] md:w-[450px]'>Latest resources</h1>

    

    </div>
        </div>

        <div className='flex flex-col items-center justify-center'>
          <div className='grid grid-cols-1 md:grid-cols-3 gap-[30px] mt-[50px]'>
            {
              resources.map((item)=>{
              return( <div className='md:w-[220px] bg-white rounded-2xl shadow h-[250px] flex flex-col items-center p-4 '>
                <Image src={item.img} width={200} height={100}/>
                <div className='mt-[10px]'>
                  <p className='text-sm'>APPS - {item.date}</p>
                  <h2 className='font-bold text-sm mt-[7px] mb-[10px]'>{item.heading}</h2>
                  <span className='mt-[20px] font-bold text-sm text-[#0582CA]'>{item.more}</span>
                </div>
              </div>) 
              })
            }
          </div>
          <div className='flex gap-[30px] mt-[50px]'>
            <button className="bg-white p-3 rounded-2xl w-[230px] text-[#0582CA]  h-[60px] shadow flex gap-[20px] items-center justify-center text-sm font-bold cursor-pointer"> <Image src="/Group 8738.png" width={30} height={100}/>Download for IOS</button>
           
            </div>
        </div>



        </div>
     </div>


     <div className='md:h-[670px] bg-[#E6E6E6]'>
      <div className='flex flex-col items-center justify-center'>  
         <div className='flex gap-[20px] mt-[50px] '>
      <h3 className='text-[#0582CA] font-bold text-2xl'>08</h3> <span className='text-2xl text-[#929292]'>-</span> <h3 className='text-[#0582CA] font-bold text-2xl'>08</h3>
    </div>
    <h1 className='font-bold md:text-4xl text-3xl md:leading-[50px] md:w-[450px] text-center'>Download the crypto<br/> wallet of the future</h1>

    <div className='flex gap-[30px] mt-[50px] flex-col md:flex-row'>
            <button className="bg-white p-3 rounded-2xl w-[230px] text-[#0582CA]  h-[60px] shadow flex gap-[20px] items-center justify-center text-sm font-bold cursor-pointer"> <Image src="/Group 8738.png" width={30} height={100}/>Download for IOS</button>
            <button className="bg-white shadow p-3 rounded-2xl w-[230px] text-[#0582CA] h-[60px] flex gap-[20px] items-center justify-center text-sm font-bold cursor-pointer"><Image src="/Group 8739.png" width={30} height={100}/>Download For Apple</button>
            </div>

            <div className="relative mt-[50px]">

            <div className='absolute -left-[20px] top-[00px]'>
            <Image src="/dollar-dollar-color.png" width={70} height={50}/>
            </div>
            <div className='absolute right-[0px] top-[00px]'>
            <Image src="/eth-dynamic-color.png" width={70} height={50}/>
            </div>
            <div className='absolute right-[50px] bottom-0'>
            <Image src="/yuan-dynamic-color (1).png" width={70} height={50}/>
            </div>
            <Image src="/Group 8696.png" width={300} height={100}/>

            </div>
      </div>

     </div>


     <div className='mt-[50px] md:h-[200px] py-4'>

      <div className="flex justify-around md:items-center flex-col md:flex-row'">

        <div className='md:w-[400px] px-3'>
          <h1 className='font-bold text-2xl'>Breew</h1>

          <p>Breew gives you the opportunity to buy rapidly growing crypto currency from your phone</p>
        </div>

      <div className='flex gap-[30px] mt-[50px] flex-col md:flex-row px-3'>
            <button className="bg-white p-3 rounded-2xl w-[230px] text-[#0582CA]  h-[60px] shadow flex gap-[20px] items-center justify-center text-sm font-bold cursor-pointer"> <Image src="/Group 8738.png" width={30} height={100}/>Download for IOS</button>
            <button className="bg-white shadow p-3 rounded-2xl w-[230px] text-[#0582CA] h-[60px] flex gap-[20px] items-center justify-center text-sm font-bold cursor-pointer"><Image src="/Group 8739.png" width={30} height={100}/>Download For Apple</button>
            </div>


      </div>

     </div>

     <hr className='mb-[80px]'/>

     <Footer/>
     
    </>
  )
}
